name: Publish WebApp Docker Container

on:
  push:
    tags:
      - 'web-app-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v4
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build the Docker image and tag
      run: docker build -f reqifviewer/Dockerfile -t stariongroup/reqifviewer:latest -t stariongroup/reqifviewer:${{ steps.vars.outputs.tag }} .
    - name: push $RELEASE_VERSION tag
      run: docker push stariongroup/reqifviewer:${{ steps.vars.outputs.tag }}
    - name: push latest tag
      run: docker push stariongroup/reqifviewer:latest