name: Publish WebApp Docker Container

on:
  push:
    tags:
      - 'web-app-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v4

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image, include SBOM and Provenance, and push
      run: |
        docker buildx build \
          --platform=linux/amd64 \
          -f reqifviewer/Dockerfile \
          -t stariongroup/reqifviewer:latest \
          -t stariongroup/reqifviewer:${{ steps.vars.outputs.tag }} \
          --sbom=true \
          --provenance=true \
          --push .